# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Verifying the GitHub WorkFlow

on:
  #push:
  # branches: [ "main" ]
  # Allow you to run the workflow manually from the action tab
  workflow_dispatch:
env:
  GLOBAL_ENV: org level variable
jobs:

  build:
    runs-on: 
     - self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: print Secrete and Variables
      run: echo "Secreate USER_EMAIL1 ${{ secrets.USER_EMAIL1 }} and USER_EMAIL ${{ vars.USER_EMAIL }} and var is  ${{ vars.API_TOKEN }}"
    - name: Import Script Parameter
      if: always()
      run: |
          json_string=`cat version-release.json`
          echo app version is $json_string
    - name: Test with pytest
      run: |
        echo build don
    - name: Display local environment variable
      env:
        VERSION_PREFIX: MyPrefix
      run: |
        echo We can use a variable multiple time: $VERSION_PREFIX
        echo $GLOBAL_ENV
        CHECK_VAL=karthik
        echo $CHECK_VAL
        echo inside a multi-line script: $VERSION_PREFIX
